[package]
name = "ca-bundle-inspector"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features=["derive"] }
pem = { version = "3.0.4", default-features = false }
